spring:
    application:
        name: spring-app

    datasource:
        url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:spring_app_db}?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true
        username: ${DB_USERNAME:root}
        password: ${DB_PASSWORD:123456}
        driver-class-name: com.mysql.cj.jdbc.Driver
        hikari:
            maximum-pool-size: ${DB_POOL_SIZE:50}
            minimum-idle: ${DB_MIN_IDLE:10}
            connection-timeout: ${DB_CONNECTION_TIMEOUT:30000}
            idle-timeout: ${DB_IDLE_TIMEOUT:600000}
            max-lifetime: ${DB_MAX_LIFETIME:1800000}
            leak-detection-threshold: ${DB_LEAK_DETECTION:60000}
            validation-timeout: ${DB_VALIDATION_TIMEOUT:5000}
            keepalive-time: ${DB_KEEPALIVE_TIME:0}

    jpa:
        hibernate:
            ddl-auto: ${JPA_DDL_AUTO:update}
        show-sql: ${JPA_SHOW_SQL:true}
        properties:
            hibernate:
                jdbc:
                    "[batch_size]": ${JPA_BATCH_SIZE:25}
                    "[fetch_size]": ${JPA_FETCH_SIZE:50}
                    "[time_zone]": UTC
                "[order_inserts]": true
                "[order_updates]": true
                "[batch_versioned_data]": true
                "[format_sql]": ${JPA_FORMAT_SQL:true}
                "[use_sql_comments]": ${JPA_USE_SQL_COMMENTS:false}
    
    jwt:
        signer-key: ${JWT_SIGNER_KEY:9BZQWCbJ1dex4l/xmilDKuXfuLYecSCCF9B44x1s/m+BOlXGjQ7cjdXSU9rEoMyR}
        expiration-hours: ${JWT_EXPIRATION_HOURS:24}
        cleanup:
            expired-tokens-interval: ${JWT_CLEANUP_EXPIRED_INTERVAL:1800000}
            deep-cleanup-cron: ${JWT_CLEANUP_DEEP_CRON:0 0 2 * * ?}
            orphaned-cleanup-cron: ${JWT_CLEANUP_ORPHANED_CRON:0 0 3 * * SUN}
            deep-cleanup-days: ${JWT_CLEANUP_DEEP_DAYS:7}
            active-tokens-interval: ${JWT_CLEANUP_ACTIVE_INTERVAL:1800000}

management:
    endpoints:
        web:
            exposure:
                include: health,info,metrics,prometheus
    endpoint:
        health:
            show-details: when-authorized
    metrics:
        export:
            prometheus:
                enabled: true

logging:
    level:
        com.vietlong.spring_app: INFO
        org.springframework.security: WARN
        "[org.hibernate.SQL]": DEBUG
        "[org.hibernate.type.descriptor.sql.BasicBinder]": TRACE
    pattern:
        console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
        file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    file:
        name: logs/spring-app.log
        max-size: 10MB
        max-history: 30
